# Generated by Django 5.1.1 on 2024-09-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoitem',
            name='mango_id',
            field=models.CharField(default=str, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
