# Generated by Django 5.1.1 on 2024-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mango_analysis", "0002_mangoitem_mango_id_alter_mangoitem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mangoitem",
            name="mango_id",
            field=models.CharField(max_length=50),
        ),
    ]
